subscription_id: 883c9081-23ed-4674-95c5-45c74834e093
resource_group_name: stc-genai-dev-pt-rg
location: westeurope
app_insights:
  name: stcgenaidevptain
  internet_ingestion_enabled: true
  internet_query_enabled: true
key_vault:
  name: stcgenaidevptkvl
  purge_protection_enabled: false
  public_network_access_enabled: false
container_registry:
  name: stcgenaidevptcon
landing:
  storage_account_name: stcgenaidevpts01
open_ai:
  name: stcgenaidevptswc
  location: swedencentral
  deployments: {
      gpt-4o-mini:
        {
          name: "gpt-4o-mini-2024-07-18",
          model:
            { 
              format: "OpenAI", 
              name: "gpt-4o-mini", 
              version: "2024-07-18"
            },
          scale: { 
            type: "Standard",
            count: 100
          }
        }
    }

ai_services:
  name: stcgenaidevptais
  location: westeurope
document_intelligence:
  name: stcgenaidevptdoc
ai_language:
  name: stcgenaidevptlng
ai_search:
  name: stcgenaidevptsch
  location: francecentral
aml:
  name: stcgenaidevptaml
  storage_account_name: stcgenaidevpts02

subnet:
  name: DevelopmentSubnet

function_app:
  name: stcgenaidevptfna
  storage_account_name: stcgenaidevpts03
  service_plan_name: stcgenaidevptfnp
  subnet_name: FunctionAppSubnet
  docker:
    registry_server_url: https://stcgenaidevptcon.azurecr.io
    image_name: tfweptdevfunctionapp
    image_tag: latest

logic_app:
  name: stcgenaidevptlap
  storage_account_name: stcgenaidevpts04
  service_plan_name: stcgenaidevptlpn
  subnet_name: LogicAppSubnet

backend:
  key: pt/dev/services.tfstate
