subscription_id: "883c9081-23ed-4674-95c5-45c74834e093"
resource_group_name: "stcwe-rg-app-01"
location: "westeurope"

key_vault_name: "stcwekv01"
enable_telemetry: true
purge_protection_enabled: false
public_network_access_enabled: false