subscription_id: "883c9081-23ed-4674-95c5-45c74834e093"
resource_group_name: "tfwe-pt-dev-rg-app-01"
location: "westeurope"
app_insights:
  name: "tfweptdevai01"
  internet_ingestion_enabled : true
  internet_query_enabled : true
key_vault:
  name: "tfweptdevkv01"
  purge_protection_enabled: false
  public_network_access_enabled: false
container_registry:
  name: "tfweptdevcr01"
landing:
  storage_account_name: "tfweptdevstg01"
open_ai:
  name: "tfweptdevopenai01"
  location: "westeurope"
ai_services:
  name: "tfweptdevaiservices01"
  location: "westeurope"
document_intelligence:
  name: "tfweptdevdocint01"
ai_language:
  name: "tfweptdevailang01"
ai_search:
  name: "tfweptdevaisrch01"
  location: "westeurope"
aml:
  name: "tfweptdevaml01"
  storage_account_name: "tfweptdevstg02"

# vnet parameters
subnet:
  name: development

function_app:
  name: tfweptdevfunctionapp
  storage_account_name: "tfweptdevstg03"
  service_plan_name: tfweptdevfunctionapppln
  subnet_name: dev-function-app # vnet parameter
  docker:
    registry_server_url: "https://tfweptdevcr01.azurecr.io"
    image_name: tfweptdevfunctionapp
    image_tag: latest

logic_app:
  name: tfweptdevlogicapp
  storage_account_name: "tfweptdevstg04"
  service_plan_name: tfweptdevlogicapppln
  subnet_name: dev-logic-app # vnet parameter