subscription_id: "883c9081-23ed-4674-95c5-45c74834e093"
resource_group_name: "tfwe-rg-app-01"
location: "westeurope"

app_insights_name: "tfweai01"
internet_ingestion_enabled : true
internet_query_enabled : true

key_vault_name: "tfwekv01"
purge_protection_enabled: false
public_network_access_enabled: false

container_registry_name: "tfwecr01"

landing_storage_account_name: "tfwestg01"
aml_storage_account_name: "tfwestg02"
function_app_storage_account_name: "tfwestg03"
logic_app_storage_account_name: "tfwestg04"

open_ai_location: "westeurope"
open_ai_name: "tfweopenai01"

ai_services_location: "westeurope"
ai_services_name: "tfweaiservices01"

document_intelligence_name: "tfwedocint01"

aml_name: "tfweaml01"

# vnet parameters
subnet_name: development
function_app_subnet_name: dev-function-app
logic_app_subnet_name: dev-logic-app

