subscription_id: 883c9081-23ed-4674-95c5-45c74834e093
resource_group_name: stc-genai-dev-tr-rg
location: westeurope
vnet:
  subnet:
    name: DevelopmentSubnet
backend:
  key: tr/dev/services.tfstate
# services to deploy
app_insights:
  name: stcgenaidevtrain
  internet_ingestion_enabled : true
  internet_query_enabled : true
key_vault:
  name: stcgenaidevtrkvl
  purge_protection_enabled: false
  public_network_access_enabled: false
container_registry:
  name: stcgenaidevtrcon
open_ai:
  name: stcgenaidevtroai
  location: swedencentral
  deployments: {
      gpt-4o-mini:
        {
          name: "gpt-4o-mini-2024-07-18",
          model:
            { 
              format: "OpenAI", 
              name: "gpt-4o-mini", 
              version: "2024-07-18"
            },
          scale: { 
            type: "Standard",
            count: 100
          }
        }
    }
ai_foundry:
  name: stcgenaidevtraif
  storage_account_name: stcgenaidevtra06
  projects: {
    "AzureOpenAI": {
      name: "azure-openai-project",
      description: "Azure Open AI project",
      friendly_name: "Azure Open AI",
      location: "westeurope"
    }
  }
ai_services:
  name: stcgenaidevtrais
  location: westeurope
  storage_account_name: stcgenaidevtra05
ai_language:
  name: stcgenaidevtrlng
aml:
  name: stcgenaidevtraml
  storage_account_name: stcgenaidevtrs02
  compute_instances: {
    # instance01: {
    #   name: "stcgenaidevtradminci01",
    #   vm_size: "Standard_DS2_v2",
    #   description: "Compute instance for development",
    #   object_id: "9caca5ad-f872-471c-ac29-c650a32783ee"
    # }
  }
uai:
  name: stcgenaidevtrciumid01
apim:
  name: "stcgenaipregrpapm"
  location: "westeurope"
  resource_group_name: stc-genai-pre-grp-rg
  deploy_apim: false
  apis :
    openai:
      name: trdevoai
      display_name: trdevoai
      path: trdevoai/openai
      backend: gtpgenaidevtroai
      policy: policies/openai/single.key.xml
      jwt:
        clientid: null
    monitoring:
      name: trdevmon
      display_name: trdevmon
      path: trdevmon/openai
      backend: gtpgenaidevtroai
      policy: policies/openai/single.key.xml
      jwt:
        clientid: null
    ailanguage:
      name: trdevlng
      display_name: trdevlng
      path: trdevlng
      policy: policies/ailanguage/single.key.xml
      jwt:
        clientid: null
landing: null
document_intelligence: null
ai_search: null
function_app: null
logic_app: null
