subscription_id: 883c9081-23ed-4674-95c5-45c74834e093
resource_group_name: stc-genai-dev-tr-rg
location: westeurope
app_insights:
  name: stcgenaidevtrain
  internet_ingestion_enabled : true
  internet_query_enabled : true
key_vault:
  name: stcgenaidevtrkvl
  purge_protection_enabled: false
  public_network_access_enabled: false
container_registry:
  name: stcgenaidevtrcon
open_ai:
  name: stcgenaidevtroai
  location: swedencentral
ai_services:
  name: stcgenaidevtrais
  location: westeurope
ai_language:
  name: stcgenaidevtrlng
aml:
  name: stcgenaidevtraml
  storage_account_name: stcgenaidevtrs02

subnet:
  name: DevelopmentSubnet

backend:
  key: tr/dev/services.tfstate
