name: 'Terraform Deploy Services'

on: 
  workflow_dispatch:
    inputs:
      market:
        description: 'Market to deploy to'     
        required: true
      environment:
        description: 'Environment to deploy to'
        required: true

jobs:
  deploy-keyvault:
    name: 'Deploy Keyvault'
    uses: ./.github/workflows/plan_apply.yaml
    with:
      market: ${{ github.event.inputs.market }}
      environment: ${{ github.event.inputs.environment }}
      az_svc: keyvault
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
