name: Terraform Deploy Virtual Network

on:
  workflow_dispatch:
    inputs:
      market:
        description: Market to deploy to
        required: true
      environment:
        description: Environment to deploy to
        required: true
      apply:
        description: Apply changes
        required: true
        default: false
        type: boolean

jobs:
  deploy-vnet:
    name: Deploy Virtual Network and Subnets
    uses: ./.github/workflows/plan_apply.yaml
    with:
      market: ${{ github.event.inputs.market }}
      environment: ${{ github.event.inputs.environment }}
      az_svc: vnet
      apply: "${{ github.event.inputs.apply }}" # https://github.com/actions/runner/issues/1483
    secrets: inherit
