name: Terraform Deploy All

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service to deploy
        required: true
        default: "dns"
        type: choice
        options:
          - dns
          - log
          - vnet
          - services
      market:
        description: Market to deploy to
        required: true
        default: "grp"
        type: choice
        options:
          - grp
          - pt
          - tr
      environment:
        description: Environment to deploy to
        required: true
        default: "prd"
        type: choice
        options:
          - dev
          - pre
          - npd
          - prd
      action:
        description: Action
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      apply:
        description: Apply changes
        required: true
        default: false
        type: boolean

jobs:
  deploy-services:
    name: Deploy Services
    uses: ./.github/workflows/plan_apply.yaml
    with:
      market: ${{ github.event.inputs.market }}
      environment: ${{ github.event.inputs.environment }}
      az_svc: ${{ github.event.inputs.service }}
      apply: "${{ github.event.inputs.apply }}" # https://github.com/actions/runner/issues/1483
      action: ${{ github.event.inputs.action }}
    secrets: inherit
