name: Terraform Destroy Services

on:
  workflow_dispatch:
    inputs:
      market:
        description: Market to deploy to
        required: true
      environment:
        description: Environment to deploy to
        required: true
      destroy:
        description: Destroy changes
        required: true
        default: false
        type: boolean

jobs:
  deploy-services:
    name: Destroy Services
    uses: ./.github/workflows/plan_destroy.yaml
    with:
      market: ${{ github.event.inputs.market }}
      environment: ${{ github.event.inputs.environment }}
      az_svc: services
      destroy: "${{ github.event.inputs.destroy }}" # https://github.com/actions/runner/issues/1483
    secrets: inherit
