name: "Terraform Import Service"

on: 
  workflow_dispatch:
    inputs:
      market:
        description: 'Market to deploy to'
        required: true
        type: choice
        options:
          - grp
          - pt
          - tr
      service:
        description: 'Service to deploy'
        required: true
        default: "dns"
        type: choice
        options:
          - vnet
          - dns
          - log
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - prd
          - npd
#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDD authenticate.
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform-import:
    name: "Terraform Import"
    runs-on: ubuntu-latest
    environment: dev
    env:
      #this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python --version
          python -m venv ${GITHUB_WORKSPACE}/.iacvenv
          ${GITHUB_WORKSPACE}/.iacvenv/bin/python -m pip install --upgrade pip
          ${GITHUB_WORKSPACE}/.iacvenv/bin/pip install -r ./scripts/requirements.txt

      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          temp_backend_output_file=$(mktemp)
          ${GITHUB_WORKSPACE}/.iacvenv/bin/python \
          ./scripts/src/backend.py \
          --backend variables/grp/prd/bed.yaml \
          --variables variables/${{ inputs.market }}/${{ inputs.environment }}/${{ inputs.service }}.yaml \
          --output-file $temp_backend_output_file
          
          # Read the backend output file and set the environment variables
          source $temp_backend_output_file

          terraform init \
          -backend-config="subscription_id=$TERRAFORM_BACKEND_AZURE_SUBSCRIPTION_ID" \
          -backend-config="resource_group_name=$TERRAFORM_BACKEND_AZURE_RESOURCE_GROUP_NAME" \
          -backend-config="storage_account_name=$TERRAFORM_BACKEND_AZURE_STORAGE_ACCOUNT_NAME" \
          -backend-config="container_name=$TERRAFORM_BACKEND_AZURE_CONTAINER_NAME" \
          -backend-config="key=$TERRAFORM_BACKEND_AZURE_KEY"

      - name: Find environemnt type
        run: |
          env_type="npd"
          input_environment="${{ inputs.environment }}"
          echo "Input environment is $input_environment"
          if [[ "$input_environment" == "prd" ]]; then
            env_type="prd"
          fi
          echo "env_type is $env_type"
          echo "env_type=$env_type" >> $GITHUB_ENV

      # Import the terraform state.
      - name: Terraform Import
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          ${GITHUB_WORKSPACE}/.iacvenv/bin/python \
          ./scripts/src/import/${{ github.event.inputs.service }}.py \
          --market ${{ github.event.inputs.market }} \
          --environment ${{ github.event.inputs.environment }} \
          --env_type $env_type \
          --folder terraform/${{ github.event.inputs.service }} \
          --variables variables/${{ github.event.inputs.market }}/${{ github.event.inputs.environment }}/${{ github.event.inputs.service }}.yaml \
          --yes

      - name: Remove virtual environment
        if: always()
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.iacvenv
