name: Upload Azure Login tool cache
on: push

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  upload_tool_cache:
    environment: grp-npd
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false