name: Get tools for self-hosted runners
on: push

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  upload_tool_cache:
    environment: grp-npd
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: List tools cache
        run: |
          ls -la ${{ runner.tool_cache }}
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: gitignore
          path: ${{ github.workspace }}/.gitignore
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: gitignore
          path: ${{ github.workspace }}/.gitignore1
      - name: Push Terraform Output to PR
        uses: actions/github-script@v7
        env:
          SUMMARY: "test"
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const body = `${process.env.SUMMARY}`;
              github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body
              })                
      - name: List _actions
        if: always()
        run: |
          # ls -la ${{ runner.tool_cache }}/../_actions
          find ${{ runner.tool_cache }}/../_actions -type f
      - name: Zip up action
        if: always()
        run: |
          cd ${{ runner.tool_cache }}/../_actions
          tar -czf /tmp/azure.login.tar.gz azure
          tar -czf /tmp/hashicorp.terraform.tar.gz hashicorp
          tar -czf /tmp/upload-artifact.tar.gz actions/upload-artifact
          tar -czf /tmp/github-script.tar.gz actions/github-script
          tar -czf /tmp/download-artifact.tar.gz actions/download-artifact